### ISSUE TITLE
View HTML

### ISSUE THREAD

**Issue by anamaria8777** [lutzroeder/Writer#3]
Any easy way to change between HTML code and preview?
Thanks

**Comment by anamaria8777** [comment]
I succeeded by adding a hidden TextBox control and a button that when pressed will hide the HtmlControl and fill the textbox with HtmlControl.SaveHtml() and show it, when press again i would just show HtmlControl, hide the textbox and call HtmlControl.LoadHtml(this.document.textbox.Text);
And i added a check to SaveAs(), in case it's called when textbox is visible to save the html with any changes.
Seems to work, but i'm not sure it's the best way :)
Thanks for your work.

**Comment by lutzroeder** [comment]
This was not a priority for this project. Goal was more to have a simple editor to replace WordPad that produces HTML instead of RTF.
